package com.matthewcmckenna.github.m3u8.util

/**
 * @see <a href="https://tools.ietf.org/html/rfc8216">HTTP Live Streaming Spec</a>
 */

// 4.3.1.1 EXTM3U
val EXTM3U = "#EXTM3U"

// 4.3.1.2 EXT-X-VERSION
val EXT_X_VERSION = "#EXT-X-VERSION"

// 4.3.2.1 EXTINF
val EXTINF = "#EXTINF"

// 4.3.2.2 EXT-X-BYTERANGE
val EXT_X_BYTERANGE = "#EXT-X-BYTERANGE"

// 4.3.2.3 EXT-X-DISCONTINUITY
val EXT_X_DISCONTINUITY = "#EXT-X-DISCONTINUITY"

// 4.3.2.4 EXT-X-KEY
val EXT_X_KEY = "#EXT-X-KEY"
val METHOD = "METHOD"
val IV = "IV"
val KEYFORMAT = "KEYFORMAT"
val KEYFORMATVERSIONS = "KEYFORMATVERSIONS"

// 4.3.2.5 EXT-X-MAP
val EXT_X_MAP = "#EXT-X-MAP"
val BYTERANGE = "BYTERANGE"

// 4.3.2.6 EXT-X-PROGRAM-DATE-TIME
val EXT_X_PROGRAM_DATE_TIME = "#EXT-X-PROGRAM-DATE-TIME"

// 4.3.2.7 EXT-X-DATERANGE
val EXT_X_DATERANGE = "#EXT-X-DATERANGE"

// 4.3.3.1 EXT-X-TARGETDURATION
val EXT_X_TARGETDURATION = "#EXT-X-TARGETDURATION"

// 4.3.3.2 EXT-X-MEDIA-SEQUENCE
val EXT_X_MEDIA_SEQUENCE = "#EXT-X-MEDIA-SEQUENCE"

// 4.3.3.3 EXT-X-DISCONTINUITY-SEQUENCE
val EXT_X_DISCONTINUITY_SEQUENCE = "#EXT-X-DISCONTINUITY-SEQUENCE"

// 4.3.3.4 EXT-X-ENDLIST
val EXT_X_ENDLIST = "#EXT-X-ENDLIST"

// 4.3.3.5 EXT-X-PLAYLIST-TYPE
val EXT_X_PLAYLIST_TYPE = "#EXT-X-PLAYLIST-TYPE"

// 4.3.3.6 EXT-X-I-FRAMES-ONLY
val EXT_X_I_FRAMES_ONLY = "#EXT-X-I-FRAMES-ONLY"

// 4.3.4.1 EXT-X-MEDIA
val EXT_X_MEDIA = "#EXT-X-MEDIA"
val TYPE = "TYPE"
val URI = "URI"
val GROUP_ID = "GROUP-ID"
val LANGUAGE = "LANGUAGE"
val ASSOC_LANGUAGE = "ASSOC-LANGUAGE"
val NAME = "NAME"
val DEFAULT = "DEFAULT"
val AUTOSELECT = "AUTOSELECT"
val FORCED = "FORCED"
val INSTREAM_ID = "INSTREAM-ID"
val CHARACTERISTICS = "CHARACTERISTICS"
val CHANNELS = "CHANNELS"

// 4.3.4.2 EXT-X-STREAM-INF
val EXT_X_STREAM_INF = "#EXT-X-STREAM-INF"
val BANDWIDTH = "BANDWIDTH"
val AVERAGE_BANDWIDTH = "AVERAGE-BANDWIDTH"
val CODECS = "CODECS"
val RESOLUTION = "RESOLUTION"
val FRAME_RATE = "FRAME-RATE"
val HDCP_LEVEL = "HDCP-LEVEL"
val AUDIO = "AUDIO"
val VIDEO = "VIDEO"
val SUBTITLES = "SUBTITLES"
val CLOSED_CAPTIONS = "CLOSED-CAPTIONS"

// 4.3.4.3 EXT-X-I-FRAME-STREAM-INF
val EXT_X_I_FRAME_STREAM_INF = "#EXT-X-I-FRAME-STREAM-INF"

// 4.3.4.4 EXT_X_SESSION_DATA
val EXT_X_SESSION_DATA = "#EXT-X-SESSION-DATA"

// 4.3.4.5 EXT-X-SESSION-KEY
val EXT_X_SESSION_KEY = "#EXT-X-SESSION-KEY"

// 4.3.5.1 EXT-X-INDEPENDENT-SEGMENTS
val EXT_X_INDEPENDENT_SEGMENTS = "#EXT-X-INDEPENDENT-SEGMENTS"

// 4.3.5.2 EXT-X-START
val EXT_X_START = "#EXT-X-START"